config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :vendas
  resources :produtos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/produto.rb
class Produto
  include Mongoid::Document
  field :nome, type: String
  field :preco, type: Float
  field :quantidade, type: Integer
  embedded_in :venda, :inverse_of => :produtos
end

app/models/venda.rb
class Venda
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  field :cliente, type: String
  field :valor, type: Float
  field :data, type: Date
  embeds_many :produtos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  def create
    params.permit!
    @venda = Venda.find(params[:venda_id])
    @produto = @venda.produtos.create!(params[:produto])
    redirect_to @venda, :notice => "Produto Cadastrado!"
  end
end

app/controllers/vendas_controller.rb
class VendasController < ApplicationController
  before_action :set_venda, only: [:show, :edit, :update, :destroy]

  # GET /vendas
  # GET /vendas.json
  def index
    @vendas = Venda.all
  end

  # GET /vendas/1
  # GET /vendas/1.json
  def show
  end

  # GET /vendas/new
  def new
    @venda = Venda.new
  end

  # GET /vendas/1/edit
  def edit
  end

  # POST /vendas
  # POST /vendas.json
  def create
    @venda = Venda.new(venda_params)

    respond_to do |format|
      if @venda.save
        format.html { redirect_to @venda, notice: 'Venda was successfully created.' }
        format.json { render :show, status: :created, location: @venda }
      else
        format.html { render :new }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendas/1
  # PATCH/PUT /vendas/1.json
  def update
    respond_to do |format|
      if @venda.update(venda_params)
        format.html { redirect_to @venda, notice: 'Venda was successfully updated.' }
        format.json { render :show, status: :ok, location: @venda }
      else
        format.html { render :edit }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendas/1
  # DELETE /vendas/1.json
  def destroy
    @venda.destroy
    respond_to do |format|
      format.html { redirect_to vendas_url, notice: 'Venda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venda
      @venda = Venda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venda_params
      params.require(:venda).permit(:cliente, :valor, :data, :produto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sigma</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vendas/_form.html.erb
<%= form_for(venda) do |f| %>
  <% if venda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(venda.errors.count, "error") %> prohibited this venda from being saved:</h2>

      <ul>
      <% venda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cliente %>
    <%= f.text_field :cliente %>
  </div>

  <div class="field">
    <%= f.label :valor %>
    <%= f.text_field :valor %>
  </div>

  <div class="field">
    <%= f.label :data %>
    <%= f.date_select :data %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendas/edit.html.erb
<h1>Editing Venda</h1>

<%= render 'form', venda: @venda %>

<%= link_to 'Show', @venda %> |
<%= link_to 'Back', vendas_path %>

app/views/vendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendas</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Valor</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendas.each do |venda| %>
      <tr>
        <td><%= venda.cliente %></td>
        <td><%= venda.valor %></td>
        <td><%= venda.data %></td>
        <td><%= link_to 'Show', venda %></td>
        <td><%= link_to 'Edit', edit_venda_path(venda) %></td>
        <td><%= link_to 'Destroy', venda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venda', new_venda_path %>

app/views/vendas/new.html.erb
<h1>New Venda</h1>

<%= render 'form', venda: @venda %>
<h2>Produtos</h2>

<%= link_to 'Back', vendas_path %>

app/views/vendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @venda.cliente %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @venda.valor %>
</p>

<p>
  <strong>Data:</strong>
  <%= @venda.data %>
</p>

<% if @venda.produtos.size > 0 %>
  <h3>produtos</h3>    
  <% for produto in @venda.produtos %>
    <%= produto.nome%>
    <%= produto.quantidade%>
    <%= produto.preco%>
  <% end %>
<% end %>

<h2>Cadastrar Produtos</h2>
<%= form_for [@venda, Produto.new] do |f|%>
  <%= f.label :nome%> <%= f.text_field :nome %>
  <%= f.label :quantidade%> <%= f.number_field :quantidade %>
  <%= f.label :preco%> <%= f.number_field :preco %>
  <%= f.submit %>
<% end %>

<%= link_to 'Edit', edit_venda_path(@venda) %> |
<%= link_to 'Back', vendas_path %>